### ISSUE TITLE
OFFS

### ISSUE THREAD

**Issue by RhysU** [jab/unfortunately-named-programming-terms#1]

**Comment by jab** [comment]
???

**Comment by RhysU** [comment]
Not one of these is any more ambiguous in programming than it is in
non-technical English.
- Rhys

**Comment by jab** [comment]
Who said the level of ambiguity in non-technical English was the bar we should strive for?

Just today I was trying to explain the implications of using the value `None` as a key or (wait for it) _value_ in a Python `dict`. Glad this has never bothered you, but maybe you haven't taught programming to beginners as much as others have, and if you had, you'd feel differently.

Anyway, opening an issue that just says "OFFS" is pretty unfriendly!

**Comment by RhysU** [comment]
Agreed on it being unfriendly. I do appreciate the gesture of the project.

Still, caveat an a priori specified newspeak of acceptable nouns, how can
discourse in English be any clearer than the age-old nouns of daily usage?
- Rhys

**Comment by jab** [comment]
documenting unfortunately-named terms != proposing replacements

Thanks for the acknowledgment. How did you come across this anyway?

**Comment by RhysU** [comment]
Saw it on hacker news. Much of the strong response was from finding it in
this manner with an unfair expectation regarding the content.

Apologies for the harshness.
- Rhys

**Comment by jab** [comment]
Gotcha. Didn't realize someone put it on HN. Thanks again and no worries.
